services:
  - type: web
    name: trade-advice-api
    env: node
    plan: free
    region: singapore
    buildCommand: npm install
    startCommand: npm run start
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20.11.1
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_SIGNUP_TOKEN
        generateValue: true
      - key: MONGODB_URI
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        value: "https://your-flutter-web-app.com"
      - key: SOCKET_ALLOWED_ORIGINS
        value: "https://your-flutter-web-app.com"
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_FROM
        sync: false
